export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

// Connection
export const UPDATE_LOCAL_PEER_ID = 'UPDATE_LOCAL_PEER_ID'
export const UPDATE_REMOTE_PEER_ID = 'UPDATE_REMOTE_PEER_ID'
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS'
export const UPDATE_IS_CONNECTED = 'UPDATE_IS_CONNECTED'
export const UPDATE_IS_CONNECTING = 'UPDATE_IS_CONNECTING'
export const TOGGLE_SIGNALING = 'TOGGLE_SIGNALING'
export const UPDATE_SIGNALING_OFFER = 'UPDATE_SIGNALING_OFFER'
export const UPDATE_SIGNALING_ANSWER = 'UPDATE_SIGNALING_ANSWER'

// Collections
export const UPDATE_LOCAL_COLLECTIONS = 'UPDATE_LOCAL_COLLECTIONS'
export const UPDATE_REMOTE_COLLECTIONS = 'UPDATE_REMOTE_COLLECTIONS'

// Video
export const UPDATE_SELECTED_FILE = 'UPDATE_SELECTED_FILE'
export const UPDATE_REQUESTED_FILE = 'UPDATE_REQUESTED_FILE'
export const UPDATE_TRANSCODING_PROGRESS = 'UPDATE_TRANSCODING_PROGRESS'
export const UPDATE_IS_TRANSCODING_VIDEO = 'UPDATE_IS_TRANSCODING_VIDEO'
export const UPDATE_IS_TRANSCODING_AUDIO = 'UPDATE_IS_TRANSCODING_AUDIO'
export const RESET_VIDEO_STATE = 'RESET_VIDEO_STATE'

// Chatroom
export const PUSH_TO_CHATROOM_MESSAGES = 'PUSH_TO_CHATROOM_MESSAGES'
export const CLEAR_CHATROOM_MESSAGES = 'CLEAR_CHATROOM_MESSAGES'

// Notifications
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
