export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const UPDATE_REMOTE_PEER_ID = 'UPDATE_REMOTE_PEER_ID'
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS'
